# Abundance

Here is a review of existing methods.

### Model Description

### Algebra
$$\hat{N} = \frac{M_{t+1}}{1-\prod^{t}(1-p_t)}$$
$$y_{i,t} \sim Bernoulli(p_t) $$

### Simulation 

```{r simulation}
N <- 150 #True population size
n_occ <- 4 #Number of trapping occasions
p <- 0.50 #Probability of first detection

true_detections <- array(NA, dim=c(N,n_occ))
for (t in 1:n_occ){
  true_detections[,t] <- rbinom(n=N,size=1,prob=p)
}
observed <- true_detections[apply(true_detections,1,max) == 1,]
MNKA <- nrow(observed)
print( paste0("Number ever detected: ", MNKA,sep = " ") ) #number ever detected
```

### JAGS
```{r,warning=FALSE,message=FALSE,error=FALSE, results='hide',cache = TRUE}
library(R2jags)
data <- list(
  y=observed,
  nsites=nrow(observed),
  MNKA=MNKA,
  n_occ=n_occ
)

modelstring <- textConnection(
  "
  model {
  
  # Likelihood
  for(i in 1:nsites) {
    # observation model
    for(j in 1:4) {
      y[i, j] ~ dbern(p)
    }
  }
  for(t in 1:4){
    p_un[t] <- (1-p)
  }
  # Priors
  p ~ dunif(0, 1) # Uninformative prior

  # Derived values
  N <- (MNKA / (1-prod(p_un[])))
}
"
)
parameters <- c("p","N")

inits <- function() {
  list( 
    
  )
}
ni <- 10000 ; nt <- 1 ; nb <- 5000 ; nc <- 3
model <- jags(data, inits, parameters, modelstring, n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb)
```
```{r}
library(knitr)
kable(round(model$BUGSoutput$summary[c(1,3),c(1,2,3,7,8,9)],2))
```

#### Stan
```{r stan ,warning=FALSE,message=FALSE,error=FALSE, results='hide',cache = TRUE}
library(rstan)
data <- list(
  y=observed,
  nsites=nrow(observed),
  MNKA=MNKA,
  n_occ=n_occ
)
stan_model <- "
data {
  int<lower=0> MNKA;
  int<lower=0> nsites;
  int<lower=0> n_occ;
  int<lower=0,upper=1> y[MNKA, n_occ];
}

parameters {
  real<lower=0, upper=1> p;
}

model {  
 for(i in 1:nsites)
    for(j in 1:4) 
      y[i, j] ~ bernoulli_lpmf(p);
}

generated quantities {
  real N = MNKA / (1-(1-p)^4);
}
"
nc <- 4

stan.samples <- stan(model_code = stan_model, data = data, iter = 10000, chains = nc, cores = nc)
```
```{r}
library(knitr)
kable(round(summary(stan.samples)$summary[c(2,1),c(1,2,3,4,8,10,9)],2))
```

#### Comparison


```{r Comparison}

```