# Survival
## Individual-level Cormack-Jolly-Seber
## Model Name 
Model description

### Algebra

Algebraic model description in latex
Log likelihood of the state-space parametrization 
$$\mathcal{L}(\phi, p, z| y) = f(z_1|\phi) \prod_{t=2}^T f(z_t| z_{t-1}, \phi) \prod_{t=1}^T f(y_t| z_t, p)$$
State Process
$$z_{i_f} = 1$$
$$z_{i,t+1}|z_{i,t} \sim Bernoulli(z_{i,t} \phi_{i,t}) $$
Observation Process
$$y_{i,t}|z_{i,t} \sim Bernoulli(z_{i,t},p_{i,t})$$ 

### Simulation 
```{r}
n_occ <- 4                   # Number of capture occasions
marked <- rep(50, n_occ-1)   # Annual number of newly marked individuals
phi <- rep(0.65, n_occ-1)
p <- rep(0.4, n_occ-1)

# Define matrices with survival and recapture probabilities
PHI <- matrix(phi, ncol = n_occ-1, nrow = sum(marked))
P <- matrix(p, ncol = n_occ-1, nrow = sum(marked))

CH <- matrix(0, ncol = n_occ, nrow = sum(marked))
marking_occ <- rep(1:length(marked), marked[1:length(marked)])
# Fill the CH matrix
i<-1
for (i in 1:sum(marked)){
  CH[i, marking_occ[i]] <- 1       # Write an 1 at the release occasion
  if (marking_occ[i]==n_occ) next
  for (t in (marking_occ[i]+1):n_occ){
    survive_occasion <- rbinom(1, 1, PHI[i,t-1])
    if (survive_occasion==0) break 
    rp <- rbinom(1, 1, P[i,t-1])
    if (rp==1) CH[i,t] <- 1
  } #t
} #i
get.first.capture <- function(x) min(which(x!=0))
first_capture <- apply(CH, 1, get.first.capture)

get.last.capture <- function(x) max(which(x!=0))
last_capture <- apply(CH, 1, get.last.capture)
```  
### Models {.tabset}

::: {.tab}
<button class="tablinks" onclick="unrolltab(event,'JAGS')">JAGS</button>
<button class="tablinks" onclick="unrolltab(event,'NIMBLE')">NIMBLE</button>
<button class="tablinks" onclick="unrolltab(event, 'Stan')">Stan</button>
<button class="tablinks" onclick="unrolltab(event, 'Greta')">Greta</button>
::: {#JAGS .tabcontent}
#### JAGS model fit {-}
```{r,eval = FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',cache = TRUE}
library(knitr)
library(R2jags)

data <- list(
  y = CH,
  n_ind = dim(CH)[1],
  nocc = dim(CH)[2],
  f = first_capture
)
model_string <- textConnection(
  "
    model {
  
  # Likelihood
  for (i in 1:n_ind){
    z[i,f[i]] <- 1
    for (t in (f[i]+1):n_occ){
      # State process
      z[i,t] ~ dbern(phi * z[i,t-1])
      # Observation process
      y[i,t] ~ dbern(mu[i,t])
      mu[i,t] <- p * z[i,t]
    } #t
  } #i
  
  # Priors and Constraints
  phi ~ dunif(0, 1)
  p ~ dunif(0, 1)
  # Derived values
  }
"
)
parameters <- c("p","phi")
cjs.z.init <- function(ch){
state <- ch
   for (i in 1:dim(ch)[1]){
      n1 <- min(which(ch[i,]==1))
      n2 <- max(which(ch[i,]==1))
      state[i,n1:n2] <- 1
      state[i,n1] <- NA
      }
   state[state==0] <- NA
   return(state)
}
set_initial_value <- function() {
  list( 
  z = cjs.z.init(CH)  
  )
}
ni <- 10000 ; nt <- 1 ; nb <- 5000 ; nc <- 3
model <- jags(data, set_initial_value, parameters, model_string, n.chains = nc, n.thin = nt, n.iter = ni, n.burnin = nb)
```

:::
::: {#NIMBLE .tabcontent}
#### NIMBLE model fit {-}
```{r,eval = FALSE,warning=FALSE,message=FALSE,error=FALSE, results='hide',cache = TRUE}
library(nimble)
n_data <- list(
  y = CH
)
n_constants <- list(
  n_ind = dim(CH)[1],
  nocc = dim(CH)[2],
  f = first_capture
)
Nimble_Code <- nimbleCode({
 # Likelihood
  for (i in 1:n_ind){
    z[i,f[i]] <- 1
    for (t in (f[i]+1):n_occ){
      # State process
      z[i,t] ~ dbern(phi * z[i,t-1])
      # Observation process
      y[i,t] ~ dbern(mu[i,t])
      mu[i,t] <- p * z[i,t]
    } #t
  } #i
  
  # Priors and Constraints
  phi ~ dunif(0, 1)
  p ~ dunif(0, 1)
  # Derived values
})

n_params <- c("p", "phi")
cjs.z.init <- function(ch){
state <- ch
   for (i in 1:dim(ch)[1]){
      n1 <- min(which(ch[i,]==1))
      n2 <- max(which(ch[i,]==1))
      state[i,n1:n2] <- 1
      state[i,n1] <- NA
      }
   state[state==0] <- NA
   return(state)
}
n_inits <- list( 
  z = cjs.z.init(CH)
)
Nimble_Model <- nimbleModel(
  code = Nimble_Code,
  constants = n_constants,
  data = n_data,
  inits = n_inits
)
MCMC_Model <- configureMCMC(Nimble_Model, monitors = n_params, print = T, enableWAIC = F)
Model1_MCMC <- buildMCMC(MCMC_Model)
Comp_Model <- compileNimble( Nimble_Model, showCompilerOutput = TRUE )
Comp_Model <- compileNimble(Model1_MCMC, project = Nimble_Model)

niter=10000
Model_samples <- runMCMC(Comp_Model, niter = niter, nburnin=niter/2,nchains=3,summary = TRUE)
#mcmc_combo(Model_samples$samples, pars = c("N", "p"))
round(Model_samples$summary$all.chains,2)
```
:::
::: {#Stan .tabcontent}
#### Stan model fit {-}
```{r ,warning=FALSE,message=FALSE,error=FALSE, results='hide',cache = TRUE}
library(knitr)
library(rstan)

data <- list(
  CH = CH,
  n_ind = dim(CH)[1],
  n_occ = dim(CH)[2],
  f = first_capture,
  l = last_capture
)

stan_model <- "
/**
 * Cormack-Jolly-Seber Model
 * 
 * following section 1.2.1 of:
 * http://www.maths.otago.ac.nz/home/resources/theses/PhD_Matthew_Schofield.pdf
 * https://discourse.mc-stan.org/t/cjs-log-likelihood/15112
 */
data {
  int<lower=2> n_occ;                      // capture events
  int<lower=0> n_ind;                      // number of individuals
  int<lower=0, upper=n_occ+1> f[n_ind];     // f[i]: ind i first capture
  int<lower=0, upper=n_occ+1> l[n_ind];     // l[i]:  ind i last capture
  int<lower=0,upper=1> CH[n_ind,n_occ];    // CH[i,k]: individual i captured at k
}

transformed data {
  int<lower=0,upper=n_ind> n_captured[n_occ];  // n_capt[k]: num aptured at k

  n_captured = rep_array(0,n_occ);
  for (i in 1:n_ind)
    for (k in 1:n_occ)
      n_captured[k] = n_captured[k] + CH[i,k];
}

parameters {
  //vector<lower=0,upper=1>[n_occ-1] phi;  // phi[k]: Pr[alive at k + 1 | alive at k]
  //vector<lower=0,upper=1>[n_occ] p;      // p[k]: Pr[capture at k]
  real<lower=0,upper=1> phi;  // phi[k]: Pr[alive at k + 1 | alive at k]
  real<lower=0,upper=1> p;      // p[k]: Pr[capture at k]

  // note:  p[1] not used in model and hence not identified
}

transformed parameters {
  vector<lower=0,upper=1>[n_occ] chi;   // chi[k]: Pr[no capture >  k | alive at k]
  vector[n_ind] log_lik;
  {
    int k;
    chi[n_occ] = 1.0;              
    k = n_occ - 1;
    while (k > 0) {
      //chi[k] = (1 - phi[k]) + phi[k] * (1 - p[k+1]) * chi[k+1]; 
      chi[k] = (1 - phi) + phi * (1 - p) * chi[k+1];
      k = k - 1;
    }
  }
  
  for (i in 1:n_ind) {
    log_lik[i] = 0;
    if (l[i] > 0) {
      for (k in (f[i]+1):l[i]) {
        log_lik[i] +=log(phi);     // i survived from k-1 to k
        if (CH[i,k] == 1)
          log_lik[i] +=log(p);       // i captured at k
        else
          log_lik[i] +=log1m(p);     // i not captured at k
      }
      log_lik[i] +=log(chi[l[i]]);   // i not seen after last[i]
    }
  }
}

model {
  target += sum(log_lik);
}

generated quantities {
  // phi[K-1] and p(K) not identified, but product is
  real beta;
  vector<lower=0>[n_occ] pop_hat;  // population
  
  beta = phi * p;
  for (k in 1:n_occ)
    pop_hat[k] = n_captured[k] / p;  
}
"

inits <- function() list(phi = runif(1, 0, 1),
                         p = runif(1, 0, 1))

## Parameters monitored
params <- c("phi", "p")

## MCMC settings
ni <- 2000
nt <- 1
nb <- 1000
nc <- 4

stan.samples <- stan(model_code = stan_model, data = data, iter = 10000, chains = nc, cores = nc)
```
:::
::: {#Greta .tabcontent}
#### Greta  model fit {-}
```{r,eval = FALSE}
library(greta)
head(CH)
head(obs_id)
head(capture_vec)
obs_id <- apply(CH, 1, function(x) seq(min(which(x > 0)), max(which(x > 0)), by = 1)[-1])
obs_id <- unlist(obs_id)
capture_vec <- apply(CH, 1, function(x) x[min(which(x > 0)):max(which(x > 0))][-1])
capture_vec <- unlist(capture_vec)

# dummy variables
alive_data <- ones(length(obs_id))            # definitely alive
not_seen_last <- last_capture != n_occ              # ignore observations in last timestep
final_observation <- ones(sum(not_seen_last)) # final observation

capture_vec <- as_data(observed)
# priors
phi <- beta(1, 1, dim = 1)
p <- beta(1, 1, dim = 1)
# derived parameter
chi <- ones(n_occ)
for (i in seq_len(n_occ - 1)) {
  tn <- n_occ - i
  chi[tn] <- (1 - phi) + phi * (1 - p) * chi[tn + 1]
}
# likelihood
distribution(alive_data) <- bernoulli(phi)
distribution(capture_vec) <- bernoulli(p)
distribution(final_observation) <- bernoulli(chi[last_capture[not_seen_last]])

# defining the model
m <- model(phi,p) #objects to sample

# sampling
draws <- greta::mcmc(m, n_samples = 1000)
```

```{r,eval = FALSE}
plot(m)
```
:::
:::

### Comparison
```{r, echo=FALSE,warning=FALSE}
#round(model$BUGSoutput$summary[c(1,3),c(1,2,3,7)],2) #jags --> -->
#round(summary(stan.samples)$summary[c(2,1),c(1,3,4,8)],2) #stan --> -->
#summary(draws) #greta --> -->
results_df <- data.frame(
              Sampler=c("Simulated","JAGS","Stan","greta","Simulated","JAGS","Stan","greta"),
              Parameter=c("N","N","N","N","p","p","p","p"),
              Mean=c(150,149.73,149.73,149.73,NA,0.52,0.52,0.52),
              SD=c(NA,1.46,1.43,1.44,NA,0.02,0.02,0.02),
              LCL=c(NA,147.21,147.25,147.22,NA,0.48,0.48,0.48),
              UCL=c(NA,152.95,152.79,152.96,NA,0.57,0.57,0.57)
              )
library(gt)
library(tidyverse)
results_df <- data.frame(
              Sampler=c("Simulated","JAGS","Stan","greta","Simulated","JAGS","Stan","greta"),
              Parameter=c("phi","phi","phi","phi","p","p","p","p"),
              Mean=c(0.65,0.60,0.61,0.62,0.40,0.44,0.43,0.46),
              SD=c(NA,0.08,0.08,0.07,NA,0.08,0.08,0.07),
              LCL=c(NA,0.47,0.46,0.49,NA,0.29,0.28,0.32),
              UCL=c(NA,0.78,0.78,0.78,NA,0.60,0.60,0.61)
              )

results_df %>%
  dplyr::select(-Sampler,-Parameter) %>%
  gt() %>%
  tab_row_group(
    group = "p",
    rows = 5:8
  ) %>%
  tab_row_group(
    group = "phi",
    rows = 1:4
  ) %>%
  tab_header(
    title = "Estimate Comparison",
    subtitle = "Comparison of C-J-S apparent survival (phi) and recapture 
               probability (p) estimates fit using JAGS, Stan, greta."
  )
```
## Jolly-Seber